package server

import "time"

// GithubHook contains all the data needed to trigger a build from a Github Hook
type GithubHook struct {
	Action      string `json:"action,omitempty"`
	Number      int    `json:"number,omitempty"`
	PullRequest struct {
		URL      string `json:"url,omitempty"`
		ID       int    `json:"id,omitempty"`
		NodeID   string `json:"node_id,omitempty"`
		HTMLURL  string `json:"html_url,omitempty"`
		DiffURL  string `json:"diff_url,omitempty"`
		PatchURL string `json:"patch_url,omitempty"`
		IssueURL string `json:"issue_url,omitempty"`
		Number   int    `json:"number,omitempty"`
		State    string `json:"state,omitempty"`
		Locked   bool   `json:"locked,omitempty"`
		Title    string `json:"title,omitempty"`
		User     struct {
			Login             string `json:"login,omitempty"`
			ID                int    `json:"id,omitempty"`
			NodeID            string `json:"node_id,omitempty"`
			AvatarURL         string `json:"avatar_url,omitempty"`
			GravatarID        string `json:"gravatar_id,omitempty"`
			URL               string `json:"url,omitempty"`
			HTMLURL           string `json:"html_url,omitempty"`
			FollowersURL      string `json:"followers_url,omitempty"`
			FollowingURL      string `json:"following_url,omitempty"`
			GistsURL          string `json:"gists_url,omitempty"`
			StarredURL        string `json:"starred_url,omitempty"`
			SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
			OrganizationsURL  string `json:"organizations_url,omitempty"`
			ReposURL          string `json:"repos_url,omitempty"`
			EventsURL         string `json:"events_url,omitempty"`
			ReceivedEventsURL string `json:"received_events_url,omitempty"`
			Type              string `json:"type,omitempty"`
			SiteAdmin         bool   `json:"site_admin,omitempty"`
		} `json:"user,omitempty"`
		Body           string    `json:"body,omitempty"`
		CreatedAt      time.Time `json:"created_at,omitempty"`
		UpdatedAt      time.Time `json:"updated_at,omitempty"`
		ClosedAt       time.Time `json:"closed_at,omitempty"`
		MergedAt       time.Time `json:"merged_at,omitempty"`
		MergeCommitSha string    `json:"merge_commit_sha,omitempty"`
		Assignee       struct {
			AvatarURL         string `json:"avatar_url,omitempty"`
			EventsURL         string `json:"events_url,omitempty"`
			FollowersURL      string `json:"followers_url,omitempty"`
			FollowingURL      string `json:"following_url,omitempty"`
			GistsURL          string `json:"gists_url,omitempty"`
			GravatarID        string `json:"gravatar_id,omitempty"`
			HTMLURL           string `json:"html_url,omitempty"`
			ID                int    `json:"id,omitempty"`
			Login             string `json:"login,omitempty"`
			NodeID            string `json:"node_id,omitempty"`
			OrganizationsURL  string `json:"organizations_url,omitempty"`
			ReceivedEventsURL string `json:"received_events_url,omitempty"`
			ReposURL          string `json:"repos_url,omitempty"`
			SiteAdmin         bool   `json:"site_admin,omitempty"`
			StarredURL        string `json:"starred_url,omitempty"`
			SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
			Type              string `json:"type,omitempty"`
			URL               string `json:"url,omitempty"`
		} `json:"assignee,omitempty"`
		Assignees []struct {
			AvatarURL         string `json:"avatar_url,omitempty"`
			EventsURL         string `json:"events_url,omitempty"`
			FollowersURL      string `json:"followers_url,omitempty"`
			FollowingURL      string `json:"following_url,omitempty"`
			GistsURL          string `json:"gists_url,omitempty"`
			GravatarID        string `json:"gravatar_id,omitempty"`
			HTMLURL           string `json:"html_url,omitempty"`
			ID                int    `json:"id,omitempty"`
			Login             string `json:"login,omitempty"`
			NodeID            string `json:"node_id,omitempty"`
			OrganizationsURL  string `json:"organizations_url,omitempty"`
			ReceivedEventsURL string `json:"received_events_url,omitempty"`
			ReposURL          string `json:"repos_url,omitempty"`
			SiteAdmin         bool   `json:"site_admin,omitempty"`
			StarredURL        string `json:"starred_url,omitempty"`
			SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
			Type              string `json:"type,omitempty"`
			URL               string `json:"url,omitempty"`
		} `json:"assignees,omitempty"`
		RequestedReviewers []interface{} `json:"requested_reviewers,omitempty"`
		RequestedTeams     []interface{} `json:"requested_teams,omitempty"`
		Labels             []struct {
			Color   string `json:"color,omitempty"`
			Default bool   `json:"default,omitempty"`
			ID      int    `json:"id,omitempty"`
			Name    string `json:"name,omitempty"`
			NodeID  string `json:"node_id,omitempty"`
			URL     string `json:"url,omitempty"`
		} `json:"labels,omitempty"`
		Milestone         interface{} `json:"milestone,omitempty"`
		CommitsURL        string      `json:"commits_url,omitempty"`
		ReviewCommentsURL string      `json:"review_comments_url,omitempty"`
		ReviewCommentURL  string      `json:"review_comment_url,omitempty"`
		CommentsURL       string      `json:"comments_url,omitempty"`
		StatusesURL       string      `json:"statuses_url,omitempty"`
		Head              struct {
			Label string `json:"label,omitempty"`
			Ref   string `json:"ref,omitempty"`
			Sha   string `json:"sha,omitempty"`
			User  struct {
				Login             string `json:"login,omitempty"`
				ID                int    `json:"id,omitempty"`
				NodeID            string `json:"node_id,omitempty"`
				AvatarURL         string `json:"avatar_url,omitempty"`
				GravatarID        string `json:"gravatar_id,omitempty"`
				URL               string `json:"url,omitempty"`
				HTMLURL           string `json:"html_url,omitempty"`
				FollowersURL      string `json:"followers_url,omitempty"`
				FollowingURL      string `json:"following_url,omitempty"`
				GistsURL          string `json:"gists_url,omitempty"`
				StarredURL        string `json:"starred_url,omitempty"`
				SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
				OrganizationsURL  string `json:"organizations_url,omitempty"`
				ReposURL          string `json:"repos_url,omitempty"`
				EventsURL         string `json:"events_url,omitempty"`
				ReceivedEventsURL string `json:"received_events_url,omitempty"`
				Type              string `json:"type,omitempty"`
				SiteAdmin         bool   `json:"site_admin,omitempty"`
			} `json:"user,omitempty"`
			Repo struct {
				ID       int    `json:"id,omitempty"`
				NodeID   string `json:"node_id,omitempty"`
				Name     string `json:"name,omitempty"`
				FullName string `json:"full_name,omitempty"`
				Owner    struct {
					Login             string `json:"login,omitempty"`
					ID                int    `json:"id,omitempty"`
					NodeID            string `json:"node_id,omitempty"`
					AvatarURL         string `json:"avatar_url,omitempty"`
					GravatarID        string `json:"gravatar_id,omitempty"`
					URL               string `json:"url,omitempty"`
					HTMLURL           string `json:"html_url,omitempty"`
					FollowersURL      string `json:"followers_url,omitempty"`
					FollowingURL      string `json:"following_url,omitempty"`
					GistsURL          string `json:"gists_url,omitempty"`
					StarredURL        string `json:"starred_url,omitempty"`
					SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
					OrganizationsURL  string `json:"organizations_url,omitempty"`
					ReposURL          string `json:"repos_url,omitempty"`
					EventsURL         string `json:"events_url,omitempty"`
					ReceivedEventsURL string `json:"received_events_url,omitempty"`
					Type              string `json:"type,omitempty"`
					SiteAdmin         bool   `json:"site_admin,omitempty"`
				} `json:"owner,omitempty"`
				Private          bool      `json:"private,omitempty"`
				HTMLURL          string    `json:"html_url,omitempty"`
				Description      string    `json:"description,omitempty"`
				Fork             bool      `json:"fork,omitempty"`
				URL              string    `json:"url,omitempty"`
				ForksURL         string    `json:"forks_url,omitempty"`
				KeysURL          string    `json:"keys_url,omitempty"`
				CollaboratorsURL string    `json:"collaborators_url,omitempty"`
				TeamsURL         string    `json:"teams_url,omitempty"`
				HooksURL         string    `json:"hooks_url,omitempty"`
				IssueEventsURL   string    `json:"issue_events_url,omitempty"`
				EventsURL        string    `json:"events_url,omitempty"`
				AssigneesURL     string    `json:"assignees_url,omitempty"`
				BranchesURL      string    `json:"branches_url,omitempty"`
				TagsURL          string    `json:"tags_url,omitempty"`
				BlobsURL         string    `json:"blobs_url,omitempty"`
				GitTagsURL       string    `json:"git_tags_url,omitempty"`
				GitRefsURL       string    `json:"git_refs_url,omitempty"`
				TreesURL         string    `json:"trees_url,omitempty"`
				StatusesURL      string    `json:"statuses_url,omitempty"`
				LanguagesURL     string    `json:"languages_url,omitempty"`
				StargazersURL    string    `json:"stargazers_url,omitempty"`
				ContributorsURL  string    `json:"contributors_url,omitempty"`
				SubscribersURL   string    `json:"subscribers_url,omitempty"`
				SubscriptionURL  string    `json:"subscription_url,omitempty"`
				CommitsURL       string    `json:"commits_url,omitempty"`
				GitCommitsURL    string    `json:"git_commits_url,omitempty"`
				CommentsURL      string    `json:"comments_url,omitempty"`
				IssueCommentURL  string    `json:"issue_comment_url,omitempty"`
				ContentsURL      string    `json:"contents_url,omitempty"`
				CompareURL       string    `json:"compare_url,omitempty"`
				MergesURL        string    `json:"merges_url,omitempty"`
				ArchiveURL       string    `json:"archive_url,omitempty"`
				DownloadsURL     string    `json:"downloads_url,omitempty"`
				IssuesURL        string    `json:"issues_url,omitempty"`
				PullsURL         string    `json:"pulls_url,omitempty"`
				MilestonesURL    string    `json:"milestones_url,omitempty"`
				NotificationsURL string    `json:"notifications_url,omitempty"`
				LabelsURL        string    `json:"labels_url,omitempty"`
				ReleasesURL      string    `json:"releases_url,omitempty"`
				DeploymentsURL   string    `json:"deployments_url,omitempty"`
				CreatedAt        time.Time `json:"created_at,omitempty"`
				UpdatedAt        time.Time `json:"updated_at,omitempty"`
				PushedAt         time.Time `json:"pushed_at,omitempty"`
				GitURL           string    `json:"git_url,omitempty"`
				SSHURL           string    `json:"ssh_url,omitempty"`
				CloneURL         string    `json:"clone_url,omitempty"`
				SvnURL           string    `json:"svn_url,omitempty"`
				Homepage         string    `json:"homepage,omitempty"`
				Size             int       `json:"size,omitempty"`
				StargazersCount  int       `json:"stargazers_count,omitempty"`
				WatchersCount    int       `json:"watchers_count,omitempty"`
				Language         string    `json:"language,omitempty"`
				HasIssues        bool      `json:"has_issues,omitempty"`
				HasProjects      bool      `json:"has_projects,omitempty"`
				HasDownloads     bool      `json:"has_downloads,omitempty"`
				HasWiki          bool      `json:"has_wiki,omitempty"`
				HasPages         bool      `json:"has_pages,omitempty"`
				ForksCount       int       `json:"forks_count,omitempty"`
				MirrorURL        string    `json:"mirror_url,omitempty"`
				Archived         bool      `json:"archived,omitempty"`
				OpenIssuesCount  int       `json:"open_issues_count,omitempty"`
				License          struct {
					Key    string `json:"key,omitempty"`
					Name   string `json:"name,omitempty"`
					SpdxID string `json:"spdx_id,omitempty"`
					URL    string `json:"url,omitempty"`
					NodeID string `json:"node_id,omitempty"`
				} `json:"license,omitempty"`
				Forks         int    `json:"forks,omitempty"`
				OpenIssues    int    `json:"open_issues,omitempty"`
				Watchers      int    `json:"watchers,omitempty"`
				DefaultBranch string `json:"default_branch,omitempty"`
			} `json:"repo,omitempty"`
		} `json:"head,omitempty"`
		Base struct {
			Label string `json:"label,omitempty"`
			Ref   string `json:"ref,omitempty"`
			Sha   string `json:"sha,omitempty"`
			User  struct {
				Login             string `json:"login,omitempty"`
				ID                int    `json:"id,omitempty"`
				NodeID            string `json:"node_id,omitempty"`
				AvatarURL         string `json:"avatar_url,omitempty"`
				GravatarID        string `json:"gravatar_id,omitempty"`
				URL               string `json:"url,omitempty"`
				HTMLURL           string `json:"html_url,omitempty"`
				FollowersURL      string `json:"followers_url,omitempty"`
				FollowingURL      string `json:"following_url,omitempty"`
				GistsURL          string `json:"gists_url,omitempty"`
				StarredURL        string `json:"starred_url,omitempty"`
				SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
				OrganizationsURL  string `json:"organizations_url,omitempty"`
				ReposURL          string `json:"repos_url,omitempty"`
				EventsURL         string `json:"events_url,omitempty"`
				ReceivedEventsURL string `json:"received_events_url,omitempty"`
				Type              string `json:"type,omitempty"`
				SiteAdmin         bool   `json:"site_admin,omitempty"`
			} `json:"user,omitempty"`
			Repo struct {
				ID       int    `json:"id,omitempty"`
				NodeID   string `json:"node_id,omitempty"`
				Name     string `json:"name,omitempty"`
				FullName string `json:"full_name,omitempty"`
				Owner    struct {
					Login             string `json:"login,omitempty"`
					ID                int    `json:"id,omitempty"`
					NodeID            string `json:"node_id,omitempty"`
					AvatarURL         string `json:"avatar_url,omitempty"`
					GravatarID        string `json:"gravatar_id,omitempty"`
					URL               string `json:"url,omitempty"`
					HTMLURL           string `json:"html_url,omitempty"`
					FollowersURL      string `json:"followers_url,omitempty"`
					FollowingURL      string `json:"following_url,omitempty"`
					GistsURL          string `json:"gists_url,omitempty"`
					StarredURL        string `json:"starred_url,omitempty"`
					SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
					OrganizationsURL  string `json:"organizations_url,omitempty"`
					ReposURL          string `json:"repos_url,omitempty"`
					EventsURL         string `json:"events_url,omitempty"`
					ReceivedEventsURL string `json:"received_events_url,omitempty"`
					Type              string `json:"type,omitempty"`
					SiteAdmin         bool   `json:"site_admin,omitempty"`
				} `json:"owner,omitempty"`
				Private          bool      `json:"private,omitempty"`
				HTMLURL          string    `json:"html_url,omitempty"`
				Description      string    `json:"description,omitempty"`
				Fork             bool      `json:"fork,omitempty"`
				URL              string    `json:"url,omitempty"`
				ForksURL         string    `json:"forks_url,omitempty"`
				KeysURL          string    `json:"keys_url,omitempty"`
				CollaboratorsURL string    `json:"collaborators_url,omitempty"`
				TeamsURL         string    `json:"teams_url,omitempty"`
				HooksURL         string    `json:"hooks_url,omitempty"`
				IssueEventsURL   string    `json:"issue_events_url,omitempty"`
				EventsURL        string    `json:"events_url,omitempty"`
				AssigneesURL     string    `json:"assignees_url,omitempty"`
				BranchesURL      string    `json:"branches_url,omitempty"`
				TagsURL          string    `json:"tags_url,omitempty"`
				BlobsURL         string    `json:"blobs_url,omitempty"`
				GitTagsURL       string    `json:"git_tags_url,omitempty"`
				GitRefsURL       string    `json:"git_refs_url,omitempty"`
				TreesURL         string    `json:"trees_url,omitempty"`
				StatusesURL      string    `json:"statuses_url,omitempty"`
				LanguagesURL     string    `json:"languages_url,omitempty"`
				StargazersURL    string    `json:"stargazers_url,omitempty"`
				ContributorsURL  string    `json:"contributors_url,omitempty"`
				SubscribersURL   string    `json:"subscribers_url,omitempty"`
				SubscriptionURL  string    `json:"subscription_url,omitempty"`
				CommitsURL       string    `json:"commits_url,omitempty"`
				GitCommitsURL    string    `json:"git_commits_url,omitempty"`
				CommentsURL      string    `json:"comments_url,omitempty"`
				IssueCommentURL  string    `json:"issue_comment_url,omitempty"`
				ContentsURL      string    `json:"contents_url,omitempty"`
				CompareURL       string    `json:"compare_url,omitempty"`
				MergesURL        string    `json:"merges_url,omitempty"`
				ArchiveURL       string    `json:"archive_url,omitempty"`
				DownloadsURL     string    `json:"downloads_url,omitempty"`
				IssuesURL        string    `json:"issues_url,omitempty"`
				PullsURL         string    `json:"pulls_url,omitempty"`
				MilestonesURL    string    `json:"milestones_url,omitempty"`
				NotificationsURL string    `json:"notifications_url,omitempty"`
				LabelsURL        string    `json:"labels_url,omitempty"`
				ReleasesURL      string    `json:"releases_url,omitempty"`
				DeploymentsURL   string    `json:"deployments_url,omitempty"`
				CreatedAt        time.Time `json:"created_at,omitempty"`
				UpdatedAt        time.Time `json:"updated_at,omitempty"`
				PushedAt         time.Time `json:"pushed_at,omitempty"`
				GitURL           string    `json:"git_url,omitempty"`
				SSHURL           string    `json:"ssh_url,omitempty"`
				CloneURL         string    `json:"clone_url,omitempty"`
				SvnURL           string    `json:"svn_url,omitempty"`
				Homepage         string    `json:"homepage,omitempty"`
				Size             int       `json:"size,omitempty"`
				StargazersCount  int       `json:"stargazers_count,omitempty"`
				WatchersCount    int       `json:"watchers_count,omitempty"`
				Language         string    `json:"language,omitempty"`
				HasIssues        bool      `json:"has_issues,omitempty"`
				HasProjects      bool      `json:"has_projects,omitempty"`
				HasDownloads     bool      `json:"has_downloads,omitempty"`
				HasWiki          bool      `json:"has_wiki,omitempty"`
				HasPages         bool      `json:"has_pages,omitempty"`
				ForksCount       int       `json:"forks_count,omitempty"`
				MirrorURL        string    `json:"mirror_url,omitempty"`
				Archived         bool      `json:"archived,omitempty"`
				OpenIssuesCount  int       `json:"open_issues_count,omitempty"`
				License          struct {
					Key    string `json:"key,omitempty"`
					Name   string `json:"name,omitempty"`
					SpdxID string `json:"spdx_id,omitempty"`
					URL    string `json:"url,omitempty"`
					NodeID string `json:"node_id,omitempty"`
				} `json:"license,omitempty"`
				Forks         int    `json:"forks,omitempty"`
				OpenIssues    int    `json:"open_issues,omitempty"`
				Watchers      int    `json:"watchers,omitempty"`
				DefaultBranch string `json:"default_branch,omitempty"`
			} `json:"repo,omitempty"`
		} `json:"base,omitempty"`
		Links struct {
			Self struct {
				Href string `json:"href,omitempty"`
			} `json:"self,omitempty"`
			HTML struct {
				Href string `json:"href,omitempty"`
			} `json:"html,omitempty"`
			Issue struct {
				Href string `json:"href,omitempty"`
			} `json:"issue,omitempty"`
			Comments struct {
				Href string `json:"href,omitempty"`
			} `json:"comments,omitempty"`
			ReviewComments struct {
				Href string `json:"href,omitempty"`
			} `json:"review_comments,omitempty"`
			ReviewComment struct {
				Href string `json:"href,omitempty"`
			} `json:"review_comment,omitempty"`
			Commits struct {
				Href string `json:"href,omitempty"`
			} `json:"commits,omitempty"`
			Statuses struct {
				Href string `json:"href,omitempty"`
			} `json:"statuses,omitempty"`
		} `json:"_links,omitempty"`
		AuthorAssociation   string      `json:"author_association,omitempty"`
		Merged              bool        `json:"merged,omitempty"`
		Mergeable           bool        `json:"mergeable,omitempty"`
		Rebaseable          bool        `json:"rebaseable,omitempty"`
		MergeableState      string      `json:"mergeable_state,omitempty"`
		MergedBy            interface{} `json:"merged_by,omitempty"`
		Comments            int         `json:"comments,omitempty"`
		ReviewComments      int         `json:"review_comments,omitempty"`
		MaintainerCanModify bool        `json:"maintainer_can_modify,omitempty"`
		Commits             int         `json:"commits,omitempty"`
		Additions           int         `json:"additions,omitempty"`
		Deletions           int         `json:"deletions,omitempty"`
		ChangedFiles        int         `json:"changed_files,omitempty"`
	} `json:"pull_request,omitempty"`
	Before     string `json:"before,omitempty"`
	After      string `json:"after,omitempty"`
	Repository struct {
		ID       int    `json:"id,omitempty"`
		NodeID   string `json:"node_id,omitempty"`
		Name     string `json:"name,omitempty"`
		FullName string `json:"full_name,omitempty"`
		Owner    struct {
			Login             string `json:"login,omitempty"`
			ID                int    `json:"id,omitempty"`
			NodeID            string `json:"node_id,omitempty"`
			AvatarURL         string `json:"avatar_url,omitempty"`
			GravatarID        string `json:"gravatar_id,omitempty"`
			URL               string `json:"url,omitempty"`
			HTMLURL           string `json:"html_url,omitempty"`
			FollowersURL      string `json:"followers_url,omitempty"`
			FollowingURL      string `json:"following_url,omitempty"`
			GistsURL          string `json:"gists_url,omitempty"`
			StarredURL        string `json:"starred_url,omitempty"`
			SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
			OrganizationsURL  string `json:"organizations_url,omitempty"`
			ReposURL          string `json:"repos_url,omitempty"`
			EventsURL         string `json:"events_url,omitempty"`
			ReceivedEventsURL string `json:"received_events_url,omitempty"`
			Type              string `json:"type,omitempty"`
			SiteAdmin         bool   `json:"site_admin,omitempty"`
		} `json:"owner,omitempty"`
		Private          bool      `json:"private,omitempty"`
		HTMLURL          string    `json:"html_url,omitempty"`
		Description      string    `json:"description,omitempty"`
		Fork             bool      `json:"fork,omitempty"`
		URL              string    `json:"url,omitempty"`
		ForksURL         string    `json:"forks_url,omitempty"`
		KeysURL          string    `json:"keys_url,omitempty"`
		CollaboratorsURL string    `json:"collaborators_url,omitempty"`
		TeamsURL         string    `json:"teams_url,omitempty"`
		HooksURL         string    `json:"hooks_url,omitempty"`
		IssueEventsURL   string    `json:"issue_events_url,omitempty"`
		EventsURL        string    `json:"events_url,omitempty"`
		AssigneesURL     string    `json:"assignees_url,omitempty"`
		BranchesURL      string    `json:"branches_url,omitempty"`
		TagsURL          string    `json:"tags_url,omitempty"`
		BlobsURL         string    `json:"blobs_url,omitempty"`
		GitTagsURL       string    `json:"git_tags_url,omitempty"`
		GitRefsURL       string    `json:"git_refs_url,omitempty"`
		TreesURL         string    `json:"trees_url,omitempty"`
		StatusesURL      string    `json:"statuses_url,omitempty"`
		LanguagesURL     string    `json:"languages_url,omitempty"`
		StargazersURL    string    `json:"stargazers_url,omitempty"`
		ContributorsURL  string    `json:"contributors_url,omitempty"`
		SubscribersURL   string    `json:"subscribers_url,omitempty"`
		SubscriptionURL  string    `json:"subscription_url,omitempty"`
		CommitsURL       string    `json:"commits_url,omitempty"`
		GitCommitsURL    string    `json:"git_commits_url,omitempty"`
		CommentsURL      string    `json:"comments_url,omitempty"`
		IssueCommentURL  string    `json:"issue_comment_url,omitempty"`
		ContentsURL      string    `json:"contents_url,omitempty"`
		CompareURL       string    `json:"compare_url,omitempty"`
		MergesURL        string    `json:"merges_url,omitempty"`
		ArchiveURL       string    `json:"archive_url,omitempty"`
		DownloadsURL     string    `json:"downloads_url,omitempty"`
		IssuesURL        string    `json:"issues_url,omitempty"`
		PullsURL         string    `json:"pulls_url,omitempty"`
		MilestonesURL    string    `json:"milestones_url,omitempty"`
		NotificationsURL string    `json:"notifications_url,omitempty"`
		LabelsURL        string    `json:"labels_url,omitempty"`
		ReleasesURL      string    `json:"releases_url,omitempty"`
		DeploymentsURL   string    `json:"deployments_url,omitempty"`
		CreatedAt        time.Time `json:"created_at,omitempty"`
		UpdatedAt        time.Time `json:"updated_at,omitempty"`
		PushedAt         time.Time `json:"pushed_at,omitempty"`
		GitURL           string    `json:"git_url,omitempty"`
		SSHURL           string    `json:"ssh_url,omitempty"`
		CloneURL         string    `json:"clone_url,omitempty"`
		SvnURL           string    `json:"svn_url,omitempty"`
		Homepage         string    `json:"homepage,omitempty"`
		Size             int       `json:"size,omitempty"`
		StargazersCount  int       `json:"stargazers_count,omitempty"`
		WatchersCount    int       `json:"watchers_count,omitempty"`
		Language         string    `json:"language,omitempty"`
		HasIssues        bool      `json:"has_issues,omitempty"`
		HasProjects      bool      `json:"has_projects,omitempty"`
		HasDownloads     bool      `json:"has_downloads,omitempty"`
		HasWiki          bool      `json:"has_wiki,omitempty"`
		HasPages         bool      `json:"has_pages,omitempty"`
		ForksCount       int       `json:"forks_count,omitempty"`
		MirrorURL        string    `json:"mirror_url,omitempty"`
		Archived         bool      `json:"archived,omitempty"`
		OpenIssuesCount  int       `json:"open_issues_count,omitempty"`
		License          struct {
			Key    string `json:"key,omitempty"`
			Name   string `json:"name,omitempty"`
			SpdxID string `json:"spdx_id,omitempty"`
			URL    string `json:"url,omitempty"`
			NodeID string `json:"node_id,omitempty"`
		} `json:"license,omitempty"`
		Forks         int    `json:"forks,omitempty"`
		OpenIssues    int    `json:"open_issues,omitempty"`
		Watchers      int    `json:"watchers,omitempty"`
		DefaultBranch string `json:"default_branch,omitempty"`
	} `json:"repository,omitempty"`
	Sender struct {
		Login             string `json:"login,omitempty"`
		ID                int    `json:"id,omitempty"`
		NodeID            string `json:"node_id,omitempty"`
		AvatarURL         string `json:"avatar_url,omitempty"`
		GravatarID        string `json:"gravatar_id,omitempty"`
		URL               string `json:"url,omitempty"`
		HTMLURL           string `json:"html_url,omitempty"`
		FollowersURL      string `json:"followers_url,omitempty"`
		FollowingURL      string `json:"following_url,omitempty"`
		GistsURL          string `json:"gists_url,omitempty"`
		StarredURL        string `json:"starred_url,omitempty"`
		SubscriptionsURL  string `json:"subscriptions_url,omitempty"`
		OrganizationsURL  string `json:"organizations_url,omitempty"`
		ReposURL          string `json:"repos_url,omitempty"`
		EventsURL         string `json:"events_url,omitempty"`
		ReceivedEventsURL string `json:"received_events_url,omitempty"`
		Type              string `json:"type,omitempty"`
		SiteAdmin         bool   `json:"site_admin,omitempty"`
	} `json:"sender,omitempty"`
}
